package com.lukman.absensi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_StatusKehadiran extends EnumerationDescriptorBase {

  public EnumerationDescriptor_StatusKehadiran() {
    super(0x730a5990b02a441bL, 0x8ab7385efdf6b2a7L, 0x27029fbd4d38f905L, "StatusKehadiran", "r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/2810984752825825541");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HADIR_0 = new EnumerationDescriptor.MemberDescriptor("HADIR", "HADIR", 0x27029fbd4d38f906L, "r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/2810984752825825542");
  private final EnumerationDescriptor.MemberDescriptor myMember_SAKIT_0 = new EnumerationDescriptor.MemberDescriptor("SAKIT", "SAKIT", 0x27029fbd4d38f907L, "r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/2810984752825825543");
  private final EnumerationDescriptor.MemberDescriptor myMember_IZIN_0 = new EnumerationDescriptor.MemberDescriptor("IZIN", "IZIN", 0x27029fbd4d38f908L, "r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/2810984752825825544");
  private final EnumerationDescriptor.MemberDescriptor myMember_ALPHA_0 = new EnumerationDescriptor.MemberDescriptor("ALPHA", "ALPHA", 0x27029fbd4d38f909L, "r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/2810984752825825545");
  private final EnumerationDescriptor.MemberDescriptor myMember_NO_INFO_0 = new EnumerationDescriptor.MemberDescriptor("NO_INFO", "NO_INFO", 0x27029fbd4d38f90aL, "r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/2810984752825825546");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x730a5990b02a441bL, 0x8ab7385efdf6b2a7L, 0x27029fbd4d38f905L, 0x27029fbd4d38f906L, 0x27029fbd4d38f907L, 0x27029fbd4d38f908L, 0x27029fbd4d38f909L, 0x27029fbd4d38f90aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_HADIR_0, myMember_SAKIT_0, myMember_IZIN_0, myMember_ALPHA_0, myMember_NO_INFO_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_NO_INFO_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HADIR":
        return myMember_HADIR_0;
      case "SAKIT":
        return myMember_SAKIT_0;
      case "IZIN":
        return myMember_IZIN_0;
      case "ALPHA":
        return myMember_ALPHA_0;
      case "NO_INFO":
        return myMember_NO_INFO_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
