package com.lukman.absensi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCatatanAbsensi = createDescriptorForCatatanAbsensi();
  /*package*/ final ConceptDescriptor myConceptRecordMahasiswa = createDescriptorForRecordMahasiswa();
  /*package*/ final EnumerationDescriptor myEnumerationStatusKehadiran = new EnumerationDescriptor_StatusKehadiran();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCatatanAbsensi, myConceptRecordMahasiswa);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CatatanAbsensi:
        return myConceptCatatanAbsensi;
      case LanguageConceptSwitch.RecordMahasiswa:
        return myConceptRecordMahasiswa;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationStatusKehadiran);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCatatanAbsensi() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.lukman.absensi", "CatatanAbsensi", 0x730a5990b02a441bL, 0x8ab7385efdf6b2a7L, 0x7b0ecee824479b2fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/8867252212775492399");
    b.version(3);
    b.property("kodeMK", 0x7b0ecee824479b35L).type(PrimitiveTypeId.STRING).origin("8867252212775492405").done();
    b.property("tanggal", 0x7b0ecee824479b37L).type(PrimitiveTypeId.STRING).origin("8867252212775492407").done();
    b.property("dosen", 0x7b0ecee824479b39L).type(PrimitiveTypeId.STRING).origin("8867252212775492409").done();
    b.aggregate("daftarMahasiswa", 0x7b0ecee824479b3dL).target(0x730a5990b02a441bL, 0x8ab7385efdf6b2a7L, 0x7b0ecee824479b40L).optional(false).ordered(true).multiple(true).origin("8867252212775492413").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRecordMahasiswa() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.lukman.absensi", "RecordMahasiswa", 0x730a5990b02a441bL, 0x8ab7385efdf6b2a7L, 0x7b0ecee824479b40L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:0be6dea0-63ae-41ea-854c-761038f8edd0(com.lukman.absensi.structure)/8867252212775492416");
    b.version(3);
    b.property("nim", 0x7b0ecee824479b45L).type(PrimitiveTypeId.STRING).origin("8867252212775492421").done();
    b.property("nama", 0x7b0ecee824479b46L).type(PrimitiveTypeId.STRING).origin("8867252212775492422").done();
    b.property("status", 0x7b0ecee824479b51L).type(MetaIdFactory.dataTypeId(0x730a5990b02a441bL, 0x8ab7385efdf6b2a7L, 0x27029fbd4d38f905L)).origin("8867252212775492433").done();
    return b.create();
  }
}
