package absensi_sol.a_model;

/*Generated by MPS */


public class Absensi {
  public static void main(String[] args) {    {
      System.out.println("");
      System.out.println("");
      System.out.println("NO_INFO");
      System.out.println("");
    }


  }
}
