package com.lukman.absensi.tests;

/*Generated by MPS */


public class Absensi {
  public static void main(String[] args) {    {
      System.out.println("241524022");
      System.out.println("Joe Lian Min");
      System.out.println("HADIR");
      System.out.println("");
    }


  }
}
